server {
    listen 80;

    include /etc/nginx/conf.d/auth.conf;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
